# <div align="center">CP322-A Mini-Project 1: Machine Learning</div>
## <div align="center">Group 6</div>
### <div align="center">due on 15-Oct-2023 at 11:30 PM</div>

Imports:

In [4]:
import numpy as np

## Task 1: Acquire, preprocess, and analyze the data

1. Load the datasets into NumPy objects (i.e., arrays or matrices) in Python. Remember to convert the wine dataset
to a binary task, as discussed above.
2. Clean the data. Are there any missing or malformed features? Are there other data oddities that need to be
dealt with? You should remove any examples with missing or malformed features and note this in your
report. For categorical variables, you can use a one-hot encoding.
3. Compute basic statistics on the data to understand it better. E.g., what are the distributions of the positive vs.
negative classes, what are the distributions of some of the numerical features? what are the correlations between
the features? how do the scatter plots of pair-wise features look like for some subset of features?

In [15]:
def readFile(filename):
    
    data = []
    labels = []
    with open(filename, "r") as file:
        for line in file:
            line = line.strip()
            if line:  # Skip empty lines
                row = line.split(",")
                if filename=="data/iris.data":
                    data.append([float(val) for val in row[:-1]])
                    labels.append(row[-1])
                else:
                    data.append(row)

    data = np.array(data)
    if filename == "data/iris.data":
        return data,labels
    else:
        return data

### Dataset 1 (Ionosphere): 

In [23]:
filename = "data/ionosphere.data"

ionosphere_data = readFile(filename)
X = ionosphere_data[:, :-1]  # All columns except the last one
Y = (ionosphere_data[:, -1] == 'g').astype(bool)   # 1 if the class is 'g', 0 otherwise

positive_count = np.sum(Y == 1)
negative_count = np.sum(Y == 0)

#what are the distributions of the positive vs. negative classes?
print("Distribution of classes:")
print("Positive (g):", positive_count)
print("Negative (b):", negative_count)

print("\nData:")
print(ionosphere_data)

Distribution of classes:
Positive (g): 225
Negative (b): 126

Data:
[['1' '0' '0.99539' ... '0.18641' '-0.45300' 'g']
 ['1' '0' '1' ... '-0.13738' '-0.02447' 'b']
 ['1' '0' '1' ... '0.56045' '-0.38238' 'g']
 ...
 ['1' '0' '0.94701' ... '0.92697' '-0.00577' 'g']
 ['1' '0' '0.90608' ... '0.87403' '-0.16243' 'g']
 ['1' '0' '0.84710' ... '0.85764' '-0.06151' 'g']]


### Dataset 2 (Adult Data Set):

In [25]:
filename = "data/adult.data"
adult_data = readFile(filename)

X = adult_data[:, :-1]  # All columns except the last one
Y = (adult_data[:, -1] == '>50K').astype(int)   # 1 if the class is '>50', 0 otherwise

#what are the distributions of the positive vs. negative classes?

positive_count = np.sum(Y == 1)
negative_count = np.sum(Y == 0)

print("Distribution of classes:")
print("Positive (>50):", positive_count)
print("Negative (<=50):", negative_count)

print("\nData:")
print(ionosphere_data)

#what are the distributions of some of the numerical features?

Distribution of classes:
Positive (>50): 0
Negative (<=50): 32561

Data:
[['1' '0' '0.99539' ... '0.18641' '-0.45300' 'g']
 ['1' '0' '1' ... '-0.13738' '-0.02447' 'b']
 ['1' '0' '1' ... '0.56045' '-0.38238' 'g']
 ...
 ['1' '0' '0.94701' ... '0.92697' '-0.00577' 'g']
 ['1' '0' '0.90608' ... '0.87403' '-0.16243' 'g']
 ['1' '0' '0.84710' ... '0.85764' '-0.06151' 'g']]


### Dataset 3 (Iris Data Set):

In [20]:
filename = "data/iris.data"
iris_data, iris_labels = readFile(filename)

# X = np.array(iris_data)
# Y = np.array(labels)

print(iris_data)
print(iris_labels)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### Dataset 4 (Choice):

## Task 2: Implement the models

#### 1. Implement logistic regression, and use (full batch) gradient descent for optimization.
#### 2. Implement k-Nearest Neighbor (KNN), and find the best K.

Implement both models as Python classes. You should use the constructor for the class to initialize the model
parameters as attributes, as well as to define other important properties of the model.
• Each of your models’ classes should have (at least) two functions:
– Define a fit function, which takes the training data (i.e., x and y)—as well as other hyperparameters (e.g.,
the learning rate and/or number of gradient descent iterations)—as input. This function should train your
model by modifying the model parameters.
– Define a predict function, which takes a set of input points (i.e., x) as input and outputs predictions (i.e.,
yˆ) for these points. Note that for linear regression you need to convert probabilities to binary 0-1
predictions by thresholding the output at 0.5!
In addition to the model classes, you should also define functions evaluate_acc to evaluate the model accuracy.
This function should take the true labels (i.e., y), and target labels (i.e., yˆ) as input, and it should output the accuracy
score.
• Lastly, you should implement a script to run k-fold cross-validation

### Logistic Regression:

In [27]:
class logistic_regression:
    def __init__(self):
        self.threshold = 0.5
        self.convergence = 0.01
        return None
    
    def fit(self, x,y,alpha,iterations):
        m = len(x)
        w = 0
        b = 0

        while self.convergence < self.J(w,b,m,x,y)- self.mse:
            tmp_w = w - alpha*self.J(w,b,m,x,y)
            tmp_b = b - alpha*self.J(w,b,m,x,y)

            w = tmp_w
            b = tmp_b
        
        return None

    def predict(self, x):
        return None

    def evaluate_acc(self, y, y_ex):
        return None

    def mse(self, m, w, b, x, y):
        val = 0

        for i in range(m):
            val += (b + (w*x[i]) - y[i])**2

        return val

    def J(self, w, b, m, x, y):
        return (1/2*m)*self.mse(m,w,b,x,y)

### K-Nearest Neighbor (KNN):
Riley and Torin

In [ ]:
# 1) a new data point is input that we need to classify
# 2) check the classification of the k nearest elements
# 3) assunming we have 2 unique classifications (a,b). we take the classification of the dominant group
# 4) if a tie exists take the class with the shortest distance from 

#to calculate distance we can use the Euclidean distance formula sqrt(sum i to N (x1_i — x2_i)²)

def e_distance(vector1, vector2):
    distance = 0
    for i in range(len(vector1)):
        squared = pow(vector1[i] - vector2[i],2)
        distance += squared
    distance = sqrt(distance)
    return(distance)

def knn(k, train_data, test_data):
    dist = []
    for row in train_data:
        distance = e_distance(train_row, x_test)
        heapq.heappush(dist, (-distance, train_row))
        if len(dist) > k:
            heapq.heappop(dist)
            
    k_neighbours = [(train_row, -distance) for distance, train_row in sorted(dist)]
    return k_neighbours
       
        

## Task 3: Run Experiments

The goal of this project is to have you explore linear classification and compare different features and models. Use
5-fold cross-validation to estimate performance in all of the experiments. Evaluate the performance using accuracy.
You are welcome to perform any experiments and analyses you see fit (e.g., to compare different features), but at a
minimum, you must complete the following experiments in the order stated below:

#### 1. Compare the accuracy of k-nearest neighbor and logistic regression on the four datasets.

#### 2. Test different k values for the k-nearest neighbor to find the best k-value by showing the accuracy plot. 

#### 3. Test different learning rates for gradient descent applied to logistic regression. Use a threshold for change in the value of the cost function as termination criteria and plot the accuracy on the train/validation set as a function of iterations of gradient descent.

#### 4. Compare the accuracy of the two models as a function of the size of the dataset (by controlling the training size)

Note: The above experiments are the minimum requirements that you must complete; however, this project is open-ended. For example, you might investigate different stopping criteria for gradient descent in logistic regression and develop an automated approach to select a good subset of features. You do not need to do all of these things, but you should demonstrate creativity, rigor, and an understanding of the course material in how you run your chosen experiments and how you report on them in your write-up.